### ISSUE TITLE
is it expected that all references has author even for misc

### ISSUE THREAD

**Issue by Borda** [openjournals/openjournals-draft-action#10]
Seems after another [update to use inara](https://github.com/openjournals/openjournals-draft-action/commit/0529517cd1082b255ffdd0660fef1c674aca057b) we have the following error, but not sure if it is mandatory to have an author or we can somehow keep it empty for general pages...

```
Error running filter /usr/local/share/openjournals/data/filters/inline-cited-references.lua:
...re/openjournals/data/filters/inline-cited-references.lua:17: attempt to get length of a nil value (local 'author')
```

**Comment by tarleb** [comment]
Sorry for the late reply, this issue got lost in the cracks. There were many improvements to Inara in the meantime, so I hope this is fixed. Please reopen if any issues persist.
