### ISSUE TITLE
non-ASCII codes for authors not handled in master branch

### ISSUE THREAD

**Issue by hugoledoux** [openjournals/openjournals-draft-action#12]
I'm the editor of that paper: https://github.com/openjournals/joss-reviews/issues/3061

and the Š of the author is not displayed in the compiled PDF, while the (correct) LaTeX command is used `- name: \v{S}tefan Jaud^[corresponding author]`

If I use the GitHub Action with another repo and I use `uses: openjournals/openjournals-draft-action@v1.0` then it's fine, it's displayed properly.

This means that the auto-compiles uses master I guess, which is wrong it seems.

**Comment by tarleb** [comment]
Thanks for raising an issue. Can you try with the literal UTF-8 `Š` instead? This would be the preferred input method, as PDF via LaTeX is no longer the only output that we need to produce.

**Comment by hugoledoux** [comment]
Haha, this works.

Simple is better than complex...

**Comment by tarleb** [comment]
Great, happy to hear :)
