### ISSUE TITLE
Issue compiling the example paper in docs

### ISSUE THREAD

**Issue by VLucet** [openjournals/openjournals-draft-action#3]
Hi, I have been trying to compile the example paper on this repo (https://github.com/pedersen-fisheries-lab/sspm-paper/) just to make sure the github action works. See the failure of the GA here: https://github.com/pedersen-fisheries-lab/sspm-paper/runs/3748004847?check_suite_focus=true.

The example paper is taken from your docs and it compiles fine when I submit it to your whedon preview service https://whedon.theoj.org/.

**Comment by VLucet** [comment]
Hi @arfon I was wondering if maybe there is another way for me to use your docker image to build the paper if the GA is not working.

**Comment by arfon** [comment]
Hrm. I wonder what's going on here... @tarleb - any chance you could take a look for us?

**Comment by VLucet** [comment]
Well, it turns out the issue was the figures, the files were missing and the warnings were stopping the latex build. Sorry about that, should have seen it. 
I would suggest somehow warning users about that in the doc, or making the figures file available or maybe just commenting out that part in the example paper and add a comment as to why it's commented out. I can make a PR!

**Comment by tarleb** [comment]
Thanks for the analysis @VLucet, and sorry for the late reply. A PR to the docs would be very welcome!

**Comment by VLucet** [comment]
Np @tarleb, ive submitted a PR to the joss website repo.
